// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using StarForge.Infrastructure.Data;

#nullable disable

namespace StarForge.Infrastructure.Migrations
{
    [DbContext(typeof(StarForgeDbContext))]
    [Migration("20260609175348_RemoveRmFromUsuario")]
    partial class RemoveRmFromUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarForge.Domain.Entities.Contribuicao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("DataContribuicao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<byte>("MetodoPagamento")
                        .HasColumnType("NUMBER(2)");

                    b.Property<string>("MissaoId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<byte>("Status")
                        .HasColumnType("NUMBER(2)");

                    b.Property<string>("TierId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MissaoId");

                    b.HasIndex("TierId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_CONTRIBUICAO", (string)null);
                });

            modelBuilder.Entity("StarForge.Domain.Entities.FaseMissao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)");

                    b.Property<string>("MissaoId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("MissaoId1")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<short>("Ordem")
                        .HasColumnType("NUMBER(5)");

                    b.Property<byte>("Status")
                        .HasColumnType("NUMBER(2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("Id");

                    b.HasIndex("MissaoId")
                        .HasDatabaseName("IX_TB_FASE_MISSAO_MISSAO_ID");

                    b.HasIndex("MissaoId1");

                    b.ToTable("TB_FASE_MISSAO", (string)null);
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Hangar", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("MissaoId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("NaveId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<byte>("Status")
                        .HasColumnType("NUMBER(2)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("MissaoId");

                    b.HasIndex("NaveId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_HANGAR", (string)null);
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Missao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("DataLimite")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(1000)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<decimal>("Meta")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("NUMBER(2)");

                    b.Property<decimal>("TotalArrecadado")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TB_MISSAO", (string)null);
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Nave", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<string>("MissaoId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("MissaoId1")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Raridade")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)");

                    b.HasKey("Id");

                    b.HasIndex("MissaoId")
                        .HasDatabaseName("IX_TB_NAVE_MISSAO_ID");

                    b.HasIndex("MissaoId1");

                    b.ToTable("TB_NAVE", (string)null);
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Tier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("BeneficioDescricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<int>("LimiteVagas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MissaoId")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("MissaoId1")
                        .IsRequired()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<int>("VagasOcupadas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MissaoId")
                        .HasDatabaseName("IX_TB_TIER_MISSAO_ID");

                    b.HasIndex("MissaoId1");

                    b.ToTable("TB_TIER", (string)null);
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<int>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)");

                    b.Property<decimal>("TotalContribuido")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USUARIO_EMAIL");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Contribuicao", b =>
                {
                    b.HasOne("StarForge.Domain.Entities.Missao", "Missao")
                        .WithMany("Contribuicoes")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarForge.Domain.Entities.Tier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarForge.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Contribuicoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Missao");

                    b.Navigation("Tier");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StarForge.Domain.Entities.FaseMissao", b =>
                {
                    b.HasOne("StarForge.Domain.Entities.Missao", null)
                        .WithMany("Fases")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarForge.Domain.Entities.Missao", "Missao")
                        .WithMany()
                        .HasForeignKey("MissaoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Missao");
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Hangar", b =>
                {
                    b.HasOne("StarForge.Domain.Entities.Missao", "Missao")
                        .WithMany()
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarForge.Domain.Entities.Nave", "Nave")
                        .WithMany()
                        .HasForeignKey("NaveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarForge.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Missao");

                    b.Navigation("Nave");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Nave", b =>
                {
                    b.HasOne("StarForge.Domain.Entities.Missao", null)
                        .WithMany("Naves")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarForge.Domain.Entities.Missao", "Missao")
                        .WithMany()
                        .HasForeignKey("MissaoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Missao");
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Tier", b =>
                {
                    b.HasOne("StarForge.Domain.Entities.Missao", null)
                        .WithMany("Tiers")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarForge.Domain.Entities.Missao", "Missao")
                        .WithMany()
                        .HasForeignKey("MissaoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Missao");
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Missao", b =>
                {
                    b.Navigation("Contribuicoes");

                    b.Navigation("Fases");

                    b.Navigation("Naves");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("StarForge.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Contribuicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
